#############################################################################
# Generated by PAGE version 7.6
#  in conjunction with Tcl version 8.6
#  May 05, 2023 04:44:30 PM CEST  platform: Windows NT
set vTcl(timestamp) ""
if {![info exists vTcl(borrow)]} {
    ::vTcl::MessageBox -title Error -message  "You must open project files from within PAGE."
    exit}


set image_list { 
}
vTcl:create_project_images $image_list   ;# In image.tcl

if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_font_dft_desc)  TkDefaultFont
set vTcl(actual_gui_font_dft_name)  TkDefaultFont
set vTcl(actual_gui_font_text_desc)  TkTextFont
set vTcl(actual_gui_font_text_name)  TkTextFont
set vTcl(actual_gui_font_fixed_desc)  TkFixedFont
set vTcl(actual_gui_font_fixed_name)  TkFixedFont
set vTcl(actual_gui_font_menu_desc)  TkMenuFont
set vTcl(actual_gui_font_menu_name)  TkMenuFont
set vTcl(actual_gui_font_tooltip_desc)  TkDefaultFont
set vTcl(actual_gui_font_tooltip_name)  TkDefaultFont
set vTcl(actual_gui_font_treeview_desc)  TkDefaultFont
set vTcl(actual_gui_font_treeview_name)  TkDefaultFont
########################################### 
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) gray40
set vTcl(analog_color_p) #c3c3c3
set vTcl(analog_color_m) beige
set vTcl(tabfg1) black
set vTcl(tabfg2) black
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(actual_gui_menu_active_fg)  #000000
########################################### 
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Absolute
}




proc vTclWindow.top1 {base} {
    global vTcl
    if {$base == ""} {
        set base .top1
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    set target $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu "$top.m51" -background $vTcl(actual_gui_bg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 669x347+346+136
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1540 845
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    set toptitle "Dipse Gestor de Contactes"
    wm title $top $toptitle
    namespace eval ::widgets::${top}::ClassOption {}
    set ::widgets::${top}::ClassOption(-toptitle) $toptitle
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    button "$top.but47" \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font "TkDefaultFont" -foreground Blue \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text "Eliminar Seleccionat" 
    vTcl:DefineAlias "$top.but47" "Button1" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    button "$top.but48" \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font "TkDefaultFont" -foreground blue \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text "Modificar seleccionat" 
    vTcl:DefineAlias "$top.but48" "Button2" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    button "$top.but50" \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font "TkDefaultFont" -foreground blue \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text "Mostrar Contactes" 
    vTcl:DefineAlias "$top.but50" "Button3" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    menu "$top.m51" \
        -activebackground $vTcl(actual_gui_menu_analog) \
        -activeforeground #000000 -background $vTcl(actual_gui_menu_bg) \
        -font "TkMenuFont" -foreground $vTcl(actual_gui_menu_fg) -tearoff 0 
### SPOT dump_widget_opt A
    frame "$top.fra52" \
        -borderwidth 2 -relief groove -background $vTcl(actual_gui_bg) \
        -height 120 -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -width 247 
    vTcl:DefineAlias "$top.fra52" "Frame1" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    set site_3_0 $top.fra52
    label "$site_3_0.lab57" \
        -activebackground #f9f9f9 -activeforeground SystemButtonText \
        -anchor w -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font "TkDefaultFont" -foreground blue \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text "Nom:" 
    vTcl:DefineAlias "$site_3_0.lab57" "Label2" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    label "$site_3_0.lab58" \
        -activebackground #f9f9f9 -activeforeground SystemButtonText \
        -anchor w -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font "TkDefaultFont" -foreground blue \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text "Telèfon:" 
    vTcl:DefineAlias "$site_3_0.lab58" "Label3" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    text "$site_3_0.tex59" \
        -background white -font "TkTextFont" -foreground black \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black -width 117 -wrap word 
    $site_3_0.tex59 configure -font "TkTextFont"
    $site_3_0.tex59 insert end text
    vTcl:DefineAlias "$site_3_0.tex59" "Text1" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    text "$site_3_0.tex60" \
        -background white -font "TkTextFont" -foreground black \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black -width 118 -wrap word 
    $site_3_0.tex60 configure -font "TkTextFont"
    $site_3_0.tex60 insert end text
    vTcl:DefineAlias "$site_3_0.tex60" "Text2" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    button "$site_3_0.but47" \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font "TkDefaultFont" -foreground blue \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text "Afegir Contacte" 
    vTcl:DefineAlias "$site_3_0.but47" "Button5" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    place $site_3_0.lab57 \
        -in $site_3_0 -x 10 -y 20 -width 0 -relwidth 0.286 -height 0 \
        -relheight 0.219 -anchor nw -bordermode ignore 
    place $site_3_0.lab58 \
        -in $site_3_0 -x 10 -y 40 -width 0 -relwidth 0.26 -height 0 \
        -relheight 0.324 -anchor nw -bordermode ignore 
    place $site_3_0.tex59 \
        -in $site_3_0 -x 70 -y 20 -width 117 -relwidth 0 -height 18 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tex60 \
        -in $site_3_0 -x 70 -y 50 -width 118 -relwidth 0 -height 18 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but47 \
        -in $site_3_0 -x 110 -y 80 -width 120 -relwidth 0 -anchor nw \
        -bordermode ignore 
    label "$top.lab56" \
        -activebackground #f9f9f9 -activeforeground SystemButtonText \
        -anchor w -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font "TkDefaultFont" -foreground blue \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text "Nou Registre" 
    vTcl:DefineAlias "$top.lab56" "Label1" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    listbox "$top.lis62" \
        -background white -disabledforeground #a3a3a3 -font "TkFixedFont" \
        -foreground $vTcl(actual_gui_fg) -height 142 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -selectbackground #c4c4c4 -selectforeground black \
        -selectmode multiple -width 424 
    $top.lis62 configure -font "TkFixedFont"
    $top.lis62 insert end text
    vTcl:DefineAlias "$top.lis62" "Listbox1" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    canvas "$top.can63" \
        -background $vTcl(actual_gui_bg) -borderwidth 2 -closeenough 1.0 \
        -height 85 -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -insertbackground black -relief ridge \
        -selectbackground #c4c4c4 -selectforeground black -width 349 
    vTcl:DefineAlias "$top.can63" "Canvas2" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    button "$top.but64" \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font "TkDefaultFont" -foreground blue \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text "Sortir" 
    vTcl:DefineAlias "$top.but64" "Button4" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    message "$top.mes65" \
        -background $vTcl(actual_gui_bg) -font "TkDefaultFont" \
        -foreground red -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -padx 1 -pady 1 -text "Message" -width 80 
    vTcl:DefineAlias "$top.mes65" "Message1" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.but47 \
        -in $top -x 9 -y 312 -width 147 -relwidth 0 -height 24 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.but48 \
        -in $top -x 410 -y 310 -width 147 -relwidth 0 -height 24 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.but50 \
        -in $top -x 19 -y 104 -width 147 -relwidth 0 -height 24 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.fra52 \
        -in $top -x 420 -y 10 -width 247 -relwidth 0 -height 120 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab56 \
        -in $top -x 450 -y 0 -width 71 -relwidth 0 -height 24 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lis62 \
        -in $top -x 143 -y 139 -width 406 -relwidth 0 -height 164 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $top.can63 \
        -in $top -x 30 -y 10 -width 349 -relwidth 0 -height 85 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.but64 \
        -in $top -x 590 -y 310 -width 67 -relwidth 0 -height 24 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.mes65 \
        -in $top -x 580 -y 170 -width 80 -relwidth 0 -height 59 -relheight 0 \
        -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

proc 36 {args} {return 1}


Window show .
set btop1 ""
if {$vTcl(borrow)} {
    set btop1 .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop1 $vTcl(tops)] != -1} {
        set btop1 .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop1
Window show .top1 $btop1
if {$vTcl(borrow)} {
    $btop1 configure -background plum
}

