#############################################################################
# Generated by PAGE version 7.6
#  in conjunction with Tcl version 8.6
#  May 05, 2023 10:45:27 PM CEST  platform: Windows NT
set vTcl(timestamp) ""
if {![info exists vTcl(borrow)]} {
    ::vTcl::MessageBox -title Error -message  "You must open project files from within PAGE."
    exit}


set image_list { 
}
vTcl:create_project_images $image_list   ;# In image.tcl

if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_font_dft_desc)  TkDefaultFont
set vTcl(actual_gui_font_dft_name)  TkDefaultFont
set vTcl(actual_gui_font_text_desc)  TkTextFont
set vTcl(actual_gui_font_text_name)  TkTextFont
set vTcl(actual_gui_font_fixed_desc)  TkFixedFont
set vTcl(actual_gui_font_fixed_name)  TkFixedFont
set vTcl(actual_gui_font_menu_desc)  TkMenuFont
set vTcl(actual_gui_font_menu_name)  TkMenuFont
set vTcl(actual_gui_font_tooltip_desc)  TkDefaultFont
set vTcl(actual_gui_font_tooltip_name)  TkDefaultFont
set vTcl(actual_gui_font_treeview_desc)  TkDefaultFont
set vTcl(actual_gui_font_treeview_name)  TkDefaultFont
########################################### 
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) gray40
set vTcl(analog_color_p) #c3c3c3
set vTcl(analog_color_m) beige
set vTcl(tabfg1) black
set vTcl(tabfg2) black
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(actual_gui_menu_active_fg)  #000000
########################################### 
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Absolute
}




proc vTclWindow.top1 {base} {
    global vTcl
    if {$base == ""} {
        set base .top1
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    set target $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu "$top.m51" -background $vTcl(actual_gui_bg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 669x347+346+136
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1540 845
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    set toptitle "Dipse Gestor de Contactes"
    wm title $top $toptitle
    namespace eval ::widgets::${top}::ClassOption {}
    set ::widgets::${top}::ClassOption(-toptitle) $toptitle
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    button "$top.but47" \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font "TkDefaultFont" -foreground Blue \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text "Eliminar Seleccionat" 
    vTcl:DefineAlias "$top.but47" "Button1" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    button "$top.but48" \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font "TkDefaultFont" -foreground blue \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text "Modificar seleccionat" 
    vTcl:DefineAlias "$top.but48" "Button2" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    button "$top.but50" \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font "TkDefaultFont" -foreground blue \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text "Mostrar Contactes" 
    vTcl:DefineAlias "$top.but50" "Button3" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    menu "$top.m51" \
        -activebackground $vTcl(actual_gui_menu_analog) \
        -activeforeground #000000 -background $vTcl(actual_gui_menu_bg) \
        -font "TkMenuFont" -foreground $vTcl(actual_gui_menu_fg) -tearoff 0 
### SPOT dump_widget_opt A
    frame "$top.fra52" \
        -borderwidth 2 -relief groove -background $vTcl(actual_gui_bg) \
        -height 120 -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -width 247 
    vTcl:DefineAlias "$top.fra52" "Frame1" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    set site_3_0 $top.fra52
    label "$site_3_0.lab57" \
        -activebackground #f9f9f9 -activeforeground SystemButtonText \
        -anchor w -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font "TkDefaultFont" -foreground blue \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text "Nom:" 
    vTcl:DefineAlias "$site_3_0.lab57" "Label2" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    label "$site_3_0.lab58" \
        -activebackground #f9f9f9 -activeforeground SystemButtonText \
        -anchor w -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font "TkDefaultFont" -foreground blue \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text "Telèfon:" 
    vTcl:DefineAlias "$site_3_0.lab58" "Label3" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    text "$site_3_0.tex59" \
        -background white -font "TkTextFont" -foreground black \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black -width 117 -wrap word 
    $site_3_0.tex59 configure -font "TkTextFont"
    $site_3_0.tex59 insert end text
    vTcl:DefineAlias "$site_3_0.tex59" "Text1" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    text "$site_3_0.tex60" \
        -background white -font "TkTextFont" -foreground black \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black -width 118 -wrap word 
    $site_3_0.tex60 configure -font "TkTextFont"
    $site_3_0.tex60 insert end text
    vTcl:DefineAlias "$site_3_0.tex60" "Text2" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    button "$site_3_0.but47" \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font "TkDefaultFont" -foreground blue \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text "Afegir Contacte" 
    vTcl:DefineAlias "$site_3_0.but47" "Button5" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    place $site_3_0.lab57 \
        -in $site_3_0 -x 10 -y 20 -width 0 -relwidth 0.286 -height 0 \
        -relheight 0.219 -anchor nw -bordermode ignore 
    place $site_3_0.lab58 \
        -in $site_3_0 -x 10 -y 40 -width 0 -relwidth 0.26 -height 0 \
        -relheight 0.324 -anchor nw -bordermode ignore 
    place $site_3_0.tex59 \
        -in $site_3_0 -x 70 -y 20 -width 117 -relwidth 0 -height 18 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tex60 \
        -in $site_3_0 -x 70 -y 50 -width 118 -relwidth 0 -height 18 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but47 \
        -in $site_3_0 -x 110 -y 80 -width 120 -relwidth 0 -anchor nw \
        -bordermode ignore 
    label "$top.lab56" \
        -activebackground #f9f9f9 -activeforeground SystemButtonText \
        -anchor w -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font "TkDefaultFont" -foreground blue \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text "Nou Registre" 
    vTcl:DefineAlias "$top.lab56" "Label1" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    canvas "$top.can63" \
        -background $vTcl(actual_gui_bg) -borderwidth 2 -closeenough 1.0 \
        -height 85 -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -insertbackground black -relief ridge \
        -selectbackground #c4c4c4 -selectforeground black -width 349 
    vTcl:DefineAlias "$top.can63" "Canvas2" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    button "$top.but64" \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font "TkDefaultFont" -foreground blue \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text "Sortir" 
    vTcl:DefineAlias "$top.but64" "Button4" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    message "$top.mes65" \
        -background $vTcl(actual_gui_bg) -font "TkDefaultFont" \
        -foreground red -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -padx 1 -pady 1 -text "Message" -width 80 
    vTcl:DefineAlias "$top.mes65" "Message1" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    ttk::style configure Treeview \
         -font  "$vTcl(actual_gui_font_treeview_desc)"
    vTcl::widgets::ttk::scrolledtreeview::CreateCmd "$top.scr47" \
        -background $vTcl(actual_gui_bg) -height 15 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 30 
    vTcl:DefineAlias "$top.scr47" "Scrolledtreeview1" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A

        $base.scr47.01 configure -columns Col1 -height 4
        $base.scr47.01 configure -columns {Col1}
        $base.scr47.01 heading #0 -text {Tree}
        $base.scr47.01 heading #0 -anchor center
        $base.scr47.01 column #0 -width 195
        $base.scr47.01 column #0 -minwidth 20
        $base.scr47.01 column #0 -stretch 1
        $base.scr47.01 column #0 -anchor w
        $base.scr47.01 heading Col1 -text {Col1}
        $base.scr47.01 heading Col1 -anchor center
        $base.scr47.01 column Col1 -width 196
        $base.scr47.01 column Col1 -minwidth 20
        $base.scr47.01 column Col1 -stretch 1
        $base.scr47.01 column Col1 -anchor w
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.but47 \
        -in $top -x 9 -y 312 -width 147 -relwidth 0 -height 24 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.but48 \
        -in $top -x 410 -y 310 -width 147 -relwidth 0 -height 24 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.but50 \
        -in $top -x 10 -y 100 -width 147 -relwidth 0 -height 24 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.fra52 \
        -in $top -x 420 -y 10 -width 247 -relwidth 0 -height 120 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab56 \
        -in $top -x 450 -y 0 -width 71 -relwidth 0 -height 24 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.can63 \
        -in $top -x 30 -y 10 -width 349 -relwidth 0 -height 85 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.but64 \
        -in $top -x 590 -y 310 -width 67 -relwidth 0 -height 24 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.mes65 \
        -in $top -x 560 -y 160 -width 80 -relwidth 0 -height 59 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.scr47 \
        -in $top -x 120 -y 140 -width 410 -relwidth 0 -height 166 \
        -relheight 0 -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

proc vTclWindow.top2 {base} {
    global vTcl
    if {$base == ""} {
        set base .top2
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    set target $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu "$top.m61" -background $vTcl(actual_gui_bg) 
    wm focusmodel $top passive
    wm geometry $top 278x120+720+540
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 3844 1061
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    set toptitle "Modificar Contacte"
    wm title $top $toptitle
    namespace eval ::widgets::${top}::ClassOption {}
    set ::widgets::${top}::ClassOption(-toptitle) $toptitle
    vTcl:DefineAlias "$top" "Toplevel2" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    label "$top.lab48" \
        -activeforeground SystemButtonText -anchor w \
        -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font "TkDefaultFont" -foreground blue \
        -text "Name:" 
    vTcl:DefineAlias "$top.lab48" "Label4" vTcl:WidgetProc "Toplevel2" 1
### SPOT dump_widget_opt A
    label "$top.lab49" \
        -activeforeground SystemButtonText -anchor w \
        -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font "TkDefaultFont" -foreground blue \
        -text "Telèfon antic:" 
    vTcl:DefineAlias "$top.lab49" "Label5" vTcl:WidgetProc "Toplevel2" 1
### SPOT dump_widget_opt A
    label "$top.lab50" \
        -activeforeground SystemButtonText -anchor w \
        -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font "TkDefaultFont" -foreground blue \
        -text "Nou telèfon:" 
    vTcl:DefineAlias "$top.lab50" "Label6" vTcl:WidgetProc "Toplevel2" 1
### SPOT dump_widget_opt A
    message "$top.mes57" \
        -background $vTcl(actual_gui_bg) -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -padx 1 -pady 1 -text "Message" -width 120 
    vTcl:DefineAlias "$top.mes57" "Message3" vTcl:WidgetProc "Toplevel2" 1
### SPOT dump_widget_opt A
    message "$top.mes58" \
        -background $vTcl(actual_gui_bg) -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -padx 1 -pady 1 -text "Message" -width 120 
    vTcl:DefineAlias "$top.mes58" "Message4" vTcl:WidgetProc "Toplevel2" 1
### SPOT dump_widget_opt A
    text "$top.tex60" \
        -background white -font "TkTextFont" -foreground black -height 24 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black -width 134 -wrap word 
    $top.tex60 configure -font "TkTextFont"
    $top.tex60 insert end text
    vTcl:DefineAlias "$top.tex60" "Text4" vTcl:WidgetProc "Toplevel2" 1
### SPOT dump_widget_opt A
    menu "$top.m61" \
        -activebackground $vTcl(actual_gui_menu_analog) \
        -activeforeground #000000 -background $vTcl(actual_gui_menu_bg) \
        -font "TkMenuFont" -foreground $vTcl(actual_gui_menu_fg) -tearoff 0 
### SPOT dump_widget_opt A
    button "$top.but62" \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font "TkDefaultFont" -foreground blue \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text "Modificar Contacte" 
    vTcl:DefineAlias "$top.but62" "Button6" vTcl:WidgetProc "Toplevel2" 1
### SPOT dump_widget_opt A
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.lab48 \
        -in $top -x 10 -y 10 -width 64 -relwidth 0 -height 21 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab49 \
        -in $top -x 10 -y 30 -anchor nw -bordermode ignore 
    place $top.lab50 \
        -in $top -x 10 -y 50 -anchor nw -bordermode ignore 
    place $top.mes57 \
        -in $top -x 100 -y 10 -width 120 -relwidth 0 -height 19 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.mes58 \
        -in $top -x 100 -y 30 -width 120 -relwidth 0 -height 19 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.tex60 \
        -in $top -x 100 -y 50 -width 134 -relwidth 0 -height 24 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.but62 \
        -in $top -x 150 -y 90 -width 117 -relwidth 0 -height 24 -relheight 0 \
        -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

proc vTclWindow.top3 {base} {
    global vTcl
    if {$base == ""} {
        set base .top3
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    set target $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background $vTcl(actual_gui_bg) 
    wm focusmodel $top passive
    wm geometry $top 283x136+381+536
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 3844 1061
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    set toptitle "Eliminar Contacte"
    wm title $top $toptitle
    namespace eval ::widgets::${top}::ClassOption {}
    set ::widgets::${top}::ClassOption(-toptitle) $toptitle
    vTcl:DefineAlias "$top" "Toplevel3" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    button "$top.but63" \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font "TkDefaultFont" -foreground red \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text "Eliminar" 
    vTcl:DefineAlias "$top.but63" "Button7" vTcl:WidgetProc "Toplevel3" 1
### SPOT dump_widget_opt A
    message "$top.mes64" \
        -background $vTcl(actual_gui_bg) -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -padx 1 -pady 1 -text "Hey! Estas segur de eliminar aquest contacte?" \
        -width 140 
    vTcl:DefineAlias "$top.mes64" "Message6" vTcl:WidgetProc "Toplevel3" 1
### SPOT dump_widget_opt A
    button "$top.but65" \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font "TkDefaultFont" -foreground Blue \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text "Torna al menu" 
    vTcl:DefineAlias "$top.but65" "Button8" vTcl:WidgetProc "Toplevel3" 1
### SPOT dump_widget_opt A
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.but63 \
        -in $top -x 50 -y 90 -width 64 -relwidth 0 -height 34 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.mes64 \
        -in $top -x 80 -y 20 -width 140 -relwidth 0 -height 49 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.but65 \
        -in $top -x 150 -y 90 -width 87 -relwidth 0 -height 34 -relheight 0 \
        -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

proc 36 {args} {return 1}


Window show .
set btop1 ""
if {$vTcl(borrow)} {
    set btop1 .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop1 $vTcl(tops)] != -1} {
        set btop1 .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop1
Window show .top1 $btop1
if {$vTcl(borrow)} {
    $btop1 configure -background plum
}
set btop2 ""
if {$vTcl(borrow)} {
    set btop2 .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop2 $vTcl(tops)] != -1} {
        set btop2 .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop2
Window show .top2 $btop2
if {$vTcl(borrow)} {
    $btop2 configure -background plum
}
set btop3 ""
if {$vTcl(borrow)} {
    set btop3 .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop3 $vTcl(tops)] != -1} {
        set btop3 .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop3
Window show .top3 $btop3
if {$vTcl(borrow)} {
    $btop3 configure -background plum
}

